Apr 14 14:38:28 fedora10 setroubleshoot: [avc.ERROR] exception OSError: [Errno 104] Connection reset by peer#012Traceback (most recent call last):#012  File "/usr/lib/python2.5/site-packages/setroubleshoot/avc_audit.py", line 335, in run#012    new_data = o
Apr 14 14:38:28 fedora10 setroubleshoot: [avc.ERROR] exception
Dec 14 17:29:57 giediprime setroubleshoot: [rpc.ERROR] could not send data on socket ({unix}/var/run/setroubleshoot/setroubleshoot_server socket=0x954b614): Broken pipe                                                                                      
